theme: jekyll-theme-cayman
title: Ankit
permalink: /blog/:year/:month/:day/:title
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
